  decode(auction_status,
              'CANCELLED', 'CANCELLED',
               'AMENDED','AMENDED',
                'DRAFT', 'DRAFT',
              decode(NVL(ah.is_paused, 'N'), 'Y',  'PAUSED', 
               decode(sign(nvl(view_by_date, open_bidding_date) -sysdate),  1, 'SUBMITTED',  
               decode(sign(open_bidding_date - sysdate),  1,'PREVIEW',
                decode(sign(close_bidding_date - sysdate), 1, 'ACTIVE',
                decode(auction_status,  'ACTIVE',
                 decode(award_status, 
                  'NO',  decode(award_approval_status,  'APPROVED',  'AWARD_APPROVED',
                                                               'REJECTED', 'AWARD_REJECTED',
                                                               'INPROCESS',  'AWARD_APPROVAL_INPROCESS',
                                                               'CLOSED'),
                'PARTIAL',  decode(award_approval_status,
                                                               'APPROVED', 'AWARD_APPROVED',
                                                               'REJECTED', 'AWARD_REJECTED',
                                                               'INPROCESS', 'AWARD_APPROVAL_INPROCESS',
                                                               'AWARD_IN_PROG'),
                'AWARDED', decode(award_approval_status,
                                                               'APPROVED',   'AWARD_APPROVED',
                                                               'REJECTED',  'AWARD_REJECTED',
                                                               'INPROCESS', 'AWARD_APPROVAL_INPROCESS',
                                                               'AWARD_IN_PROG')),
               'AUCTION_CLOSED',  decode(award_status,
                                                        'NO',  'ROUND_COMPLETED',
                                                        'QUALIFIED',  'RFI_COMPLETED',
                                                        decode(outcome_status,
                                                               'NOT_ALLOCATED', 'AWARD_COMPLETED',
                                                               'PARTIALLY_ALLOCATED', 'ALLOCATION_IN_PROG',
                                                               'ALLOCATED',  'ALLOCATION_IN_PROG',
                                                               'ALLOCATION_NOT_REQUIRED',  'AWARD_COMPLETED',
                                                               outcome_status
                                                               )))))))) NEGOTIATION_STATUS,
